---
- name: Rocky Config
  hosts: rocky
  vars_prompt:
    - name: sudo_password
      prompt: "Enter sudo password for {{ ansible_user }}:"
      private: yes
  vars:
    ssh_dir: "/home/{{ ansible_user }}/.ssh"
    authorized_keys_file: "{{ ssh_dir }}/authorized_keys"
    sudoers_file: "/etc/sudoers.d/480"
    sudoers_dropin_entry: "480"
    ansible_user: deployer
    ansible_become_pass: "{{ sudo_password }}"
  tasks:
    - name: Create SSH directory
      file:
        path: "{{ ssh_dir }}"
        state: directory
        mode: '0700'

    - name: Create authorized_keys file
      file:
        path: "{{ authorized_keys_file }}"
        state: touch
        mode: '0600'
    
    - name: Copy public key to authorized_keys file
      blockinfile:
        dest: "{{ authorized_keys_file }}"
        block: "{{ pub_key }}"

    - name: Create sudoers file for 480
      file:
        path: "{{ sudoers_file }}"
        state: touch
        mode: '0440'
      become: yes

    - name: Create drop in entry in /etc/sudoers.d/480
      lineinfile:
        path: "{{ sudoers_file }}"
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        create: yes
        state: present
      become: yes
      

    - name: Change hostname
      hostname:
        name: "{{ hostname }}"
      become: yes
    
    - name: add hosts to host file
      lineinfile:
        path: /etc/hosts
        line: "127.0.1.1 {{ hostname }}"
      become: yes
    
    - name: Debug Output
      debug:
        msg: "LAN IP: {{ lan_ip }}, Prefix: {{ prefix }}, Gateway: {{ gateway }}, Domain: {{ domain }}"

    - name: run nmcli to change to static address
      nmcli:
        conn_name: "{{ device }}"
        ip4: "{{ lan_ip }}/{{ prefix }}"
        gw4: "{{ gateway }}"
        state: present
        type: ethernet
        dns4:  
          - "{{ dns }}"
          - "{{ gateway }}"
        method4: manual
      become: yes

    - name: bounce the box
      shell: 'sleep 5 && shutdown -r now'
      become: yes
      async: 1
      poll: 0
